apiVersion: nextcluster.net/v1
kind: Group
metadata: # ATTENTION: This metadata cannot be changed after creation!
  name: static-service
  namespace: nextcluster
spec:
  base:
    image: registry.nextcluster.net/pre-vm:latest
    environment:
      - PLATFORM=PAPER
      - VELOCITY_SECRET=2pOyTL6vI025
    ports:
      - port: 25565
        protocol: TCP
  maintenance: false
  maxMemory: 5000
  fallback: true
  static: true