apiVersion: v1
kind: ServiceAccount
metadata:
  name: nextcluster
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nextcluster
rules:
  - verbs:
      - get
      - list
      - create
      - delete
      - watch
      - patch
    apiGroups:
      - ''
      - apps
    resources:
      - pods
      - pods/log
      - deployments
      - services
      - statefulsets
      - events
      - configmaps
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nextcluster-role-binding
subjects:
  - kind: ServiceAccount
    name: nextcluster
    namespace: nextcluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nextcluster
