apiVersion: v1
kind: Namespace
metadata:
  name: nextcluster
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
  namespace: nextcluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manager
  template:
    metadata:
      labels:
        app: manager
    spec:
      containers:
        - name: manager
          image: registry.nextcluster.net/manager:latest
          env:
            - name: KUBERNETES_AUTH_TRYKUBECONFIG
              value: "false"